### ISSUE TITLE
Archivo "matches_chile.csv"

### ISSUE THREAD

**Issue by vgodoyd** [pablogalazcares/football-DS-projects#1]
Hola Pablo! 
Primero que todo muchas gracias por el proyecto, me estoy iniciando en el mundo del DS y estaba buscando algo que me motivara a escribir código y jugar para soltar las manos. 
Te quería comentar que quise copiar el código para entenderlo (y actualizarlo con los nuevos resultados) pero no encuentro el archivo "matches_chile.csv". Me podrías ayudar? 

Gracias!

**Comment by pablogalazcares** [comment]
Hola, @vgodoyd me alegra que te haya gustado y que ayude a motivarte en el mundo del DS. Acabo de subir el archivo "matches_chile.csv" para que puedas replicar el proyecto 🙌 

Otros comentarios: dejé las funciones en un archivo ".py" y los importo directo en el Notebook.

**Comment by vgodoyd** [comment]
Buenísimo, muchas gracias!
